// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

library Errors {
    // UniCardRegistry
    error UNICARD_REGISTRY_USER_ALREADY_HAS_COMMITMENT();
    error UNICARD_REGISTRY_PAYMENT_TOKEN_NOT_ALLOWED();
    error UNICARD_REGISTRY_NONCE_MISMATCH();
    error UNICARD_REGISTRY_REQUEST_TX_HASH_EMPTY();
    error UNICARD_REGISTRY_INVALID_SIGNATURE();
    error UNICARD_REGISTRY_REQUEST_TX_HASH_ALREADY_USED();
}
