/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as uniCardCollateralSol from "./UniCardCollateral.sol";
export type { uniCardCollateralSol };
export type { USDU } from "./USDU";
export type { UniCardRegistry } from "./UniCardRegistry";
export type { UniCardVault } from "./UniCardVault";
