/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRETHToken,
  IRETHTokenInterface,
} from "../../../src/dependencies/IRETHToken";

const _abi = [
  {
    inputs: [],
    name: "getExchangeRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRETHToken__factory {
  static readonly abi = _abi;
  static createInterface(): IRETHTokenInterface {
    return new Interface(_abi) as IRETHTokenInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IRETHToken {
    return new Contract(address, _abi, runner) as unknown as IRETHToken;
  }
}
