/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IStaderOracle,
  IStaderOracleInterface,
} from "../../../src/dependencies/IStaderOracle";

const _abi = [
  {
    inputs: [],
    name: "exchangeRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IStaderOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IStaderOracleInterface {
    return new Interface(_abi) as IStaderOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IStaderOracle {
    return new Contract(address, _abi, runner) as unknown as IStaderOracle;
  }
}
