/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IHintHelpersInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "forcePredictAdjustInterestRateUpfrontFee"
      | "getApproxHint"
      | "predictAdjustBatchInterestRateUpfrontFee"
      | "predictAdjustInterestRateUpfrontFee"
      | "predictAdjustTroveUpfrontFee"
      | "predictJoinBatchInterestRateUpfrontFee"
      | "predictOpenTroveUpfrontFee"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "forcePredictAdjustInterestRateUpfrontFee",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproxHint",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "predictAdjustBatchInterestRateUpfrontFee",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "predictAdjustInterestRateUpfrontFee",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "predictAdjustTroveUpfrontFee",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "predictJoinBatchInterestRateUpfrontFee",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "predictOpenTroveUpfrontFee",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "forcePredictAdjustInterestRateUpfrontFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproxHint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "predictAdjustBatchInterestRateUpfrontFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "predictAdjustInterestRateUpfrontFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "predictAdjustTroveUpfrontFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "predictJoinBatchInterestRateUpfrontFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "predictOpenTroveUpfrontFee",
    data: BytesLike
  ): Result;
}

export interface IHintHelpers extends BaseContract {
  connect(runner?: ContractRunner | null): IHintHelpers;
  waitForDeployment(): Promise<this>;

  interface: IHintHelpersInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  forcePredictAdjustInterestRateUpfrontFee: TypedContractMethod<
    [
      _collIndex: BigNumberish,
      _troveId: BigNumberish,
      _newInterestRate: BigNumberish
    ],
    [bigint],
    "view"
  >;

  getApproxHint: TypedContractMethod<
    [
      _collIndex: BigNumberish,
      _interestRate: BigNumberish,
      _numTrials: BigNumberish,
      _inputRandomSeed: BigNumberish
    ],
    [
      [bigint, bigint, bigint] & {
        hintId: bigint;
        diff: bigint;
        latestRandomSeed: bigint;
      }
    ],
    "view"
  >;

  predictAdjustBatchInterestRateUpfrontFee: TypedContractMethod<
    [
      _collIndex: BigNumberish,
      _batchAddress: AddressLike,
      _newInterestRate: BigNumberish
    ],
    [bigint],
    "view"
  >;

  predictAdjustInterestRateUpfrontFee: TypedContractMethod<
    [
      _collIndex: BigNumberish,
      _troveId: BigNumberish,
      _newInterestRate: BigNumberish
    ],
    [bigint],
    "view"
  >;

  predictAdjustTroveUpfrontFee: TypedContractMethod<
    [
      _collIndex: BigNumberish,
      _troveId: BigNumberish,
      _debtIncrease: BigNumberish
    ],
    [bigint],
    "view"
  >;

  predictJoinBatchInterestRateUpfrontFee: TypedContractMethod<
    [
      _collIndex: BigNumberish,
      _troveId: BigNumberish,
      _batchAddress: AddressLike
    ],
    [bigint],
    "view"
  >;

  predictOpenTroveUpfrontFee: TypedContractMethod<
    [
      _collIndex: BigNumberish,
      _borrowedAmount: BigNumberish,
      _interestRate: BigNumberish
    ],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "forcePredictAdjustInterestRateUpfrontFee"
  ): TypedContractMethod<
    [
      _collIndex: BigNumberish,
      _troveId: BigNumberish,
      _newInterestRate: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getApproxHint"
  ): TypedContractMethod<
    [
      _collIndex: BigNumberish,
      _interestRate: BigNumberish,
      _numTrials: BigNumberish,
      _inputRandomSeed: BigNumberish
    ],
    [
      [bigint, bigint, bigint] & {
        hintId: bigint;
        diff: bigint;
        latestRandomSeed: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "predictAdjustBatchInterestRateUpfrontFee"
  ): TypedContractMethod<
    [
      _collIndex: BigNumberish,
      _batchAddress: AddressLike,
      _newInterestRate: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "predictAdjustInterestRateUpfrontFee"
  ): TypedContractMethod<
    [
      _collIndex: BigNumberish,
      _troveId: BigNumberish,
      _newInterestRate: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "predictAdjustTroveUpfrontFee"
  ): TypedContractMethod<
    [
      _collIndex: BigNumberish,
      _troveId: BigNumberish,
      _debtIncrease: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "predictJoinBatchInterestRateUpfrontFee"
  ): TypedContractMethod<
    [
      _collIndex: BigNumberish,
      _troveId: BigNumberish,
      _batchAddress: AddressLike
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "predictOpenTroveUpfrontFee"
  ): TypedContractMethod<
    [
      _collIndex: BigNumberish,
      _borrowedAmount: BigNumberish,
      _interestRate: BigNumberish
    ],
    [bigint],
    "view"
  >;

  filters: {};
}
